//! Typesafe builder for [`InvocationPayload`].

use crate::{
    codec::CborCodec,
    command::Command,
    crypto::nonce::Nonce,
    envelope::{Envelope, EnvelopePayload},
    issuer::Issuer,
    promise::Promised,
    sealed::{CommandOrUnset, IssuerOrUnset, PrincipalOrUnset, ProofsOrUnset},
    time::timestamp::Timestamp,
    unset::Unset,
};
use ipld_core::{cid::Cid, ipld::Ipld};
use std::{collections::BTreeMap, marker::PhantomData};
use varsig::{
    algorithm::SignatureAlgorithm,
    signature::{verifier::Verifier, Varsig},
};

/// Typesafe builder for [`Invocation`].
#[allow(private_bounds)]
#[derive(Default, Debug, Clone)]
pub struct InvocationBuilder<
    D: Issuer,
    Iss: IssuerOrUnset = Unset,
    Audience: PrincipalOrUnset = Unset,
    Subject: PrincipalOrUnset = Unset,
    Cmd: CommandOrUnset = Unset,
    Proofs: ProofsOrUnset = Unset,
> {
    /// Issuer of the invocation.
    pub issuer: Iss,

    /// Audience of the invocation.
    pub audience: Audience,

    /// Subject of the invocation (the resource or object being accessed).
    pub subject: Subject,

    /// Cmd being invoked.
    pub command: Cmd,

    /// The arguments for the Cmd.
    pub arguments: BTreeMap<String, Promised>,

    /// Proofs of the invocation.
    pub proofs: Proofs,

    /// Cause of the invocation.
    pub cause: Option<Cid>,

    /// Expiration time of the invocation.
    pub expiration: Option<Timestamp>,

    /// The time at which this invocation claims to have been issued.
    pub issued_at: Option<Timestamp>,

    /// Extensible metadata for the delegation.
    pub meta: BTreeMap<String, Ipld>,

    /// Nonce (will be autogenerated if left blank).
    pub nonce: Option<Nonce>,

    _did: PhantomData<D>,
}

impl<D: Issuer> InvocationBuilder<D, Unset, Unset, Unset, Unset, Unset> {
    /// Creates a blank [`InvocationBuilder`] instance.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            issuer: Unset,
            audience: Unset,
            subject: Unset,
            command: Unset,
            arguments: BTreeMap::new(),
            proofs: Unset,
            cause: None,
            expiration: None,
            issued_at: None,
            meta: BTreeMap::new(),
            nonce: None,
            _did: PhantomData,
        }
    }
}

#[allow(private_bounds)]
impl<
        D: Issuer,
        Iss: IssuerOrUnset,
        Audience: PrincipalOrUnset,
        Subject: PrincipalOrUnset,
        Cmd: CommandOrUnset,
        Proofs: ProofsOrUnset,
    > InvocationBuilder<D, Iss, Audience, Subject, Cmd, Proofs>
{
    /// Sets the `issuer` field of the invocation.
    #[must_use]
    pub fn issuer(self, issuer: D) -> InvocationBuilder<D, D, Audience, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `audience` field of the invocation.
    #[must_use]
    pub fn audience(
        self,
        audience: D::Principal,
    ) -> InvocationBuilder<D, Iss, D::Principal, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `subject` field of the invocation.
    #[must_use]
    pub fn subject(
        self,
        subject: D::Principal,
    ) -> InvocationBuilder<D, Iss, Audience, D::Principal, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `command` field of the invocation.
    #[must_use]
    pub fn command(
        self,
        command: Vec<String>,
    ) -> InvocationBuilder<D, Iss, Audience, Subject, Command, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: Command::new(command),
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `arguments` field of the invocation.
    #[must_use]
    pub fn arguments(
        self,
        arguments: BTreeMap<String, Promised>,
    ) -> InvocationBuilder<D, Iss, Audience, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `proofs` field of the invocation.
    #[must_use]
    pub fn proofs(
        self,
        proofs: Vec<Cid>,
    ) -> InvocationBuilder<D, Iss, Audience, Subject, Cmd, Vec<Cid>> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `expiration` field of the invocation.
    #[must_use]
    pub fn expiration(
        self,
        expiration: Timestamp,
    ) -> InvocationBuilder<D, Iss, Audience, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: Some(expiration),
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `issued_at` field of the invocation.
    #[must_use]
    pub fn issued_at(
        self,
        issued_at: Timestamp,
    ) -> InvocationBuilder<D, Iss, Audience, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: Some(issued_at),
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `issued_at` field of the invocation to the current system time.
    #[must_use]
    pub fn issue_now(self) -> InvocationBuilder<D, Iss, Audience, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: Some(Timestamp::now()),
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `meta` field of the invocation.
    #[must_use]
    pub fn meta(
        self,
        meta: BTreeMap<String, Ipld>,
    ) -> InvocationBuilder<D, Iss, Audience, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `nonce` field of the invocation.
    #[must_use]
    pub fn nonce(self, nonce: Nonce) -> InvocationBuilder<D, Iss, Audience, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: Some(nonce),
            _did: PhantomData,
        }
    }
}

/// Build error type for invocation builder.
#[derive(Debug, thiserror::Error)]
pub enum BuildError {
    /// Encoding error.
    #[error("Encoding error: {0}")]
    EncodingError(String),

    /// Signing error.
    #[error("Signing error: {0}")]
    SigningError(#[from] signature::Error),
}

/// Building methods that use async signing.
///
/// This impl block uses async signing via the [`Issuer`] trait (which is a `Signer`),
/// which works with both native `ed25519_dalek` signers and `WebCrypto` signers.
#[allow(clippy::mismatching_type_param_order)]
impl<D: Issuer> InvocationBuilder<D, D, D::Principal, D::Principal, Command, Vec<Cid>> {
    /// Builds the complete, signed [`Invocation`].
    ///
    /// Uses the issuer (set via `.issuer()`) to sign the invocation.
    /// The signing is performed asynchronously via [`Issuer::sign()`].
    ///
    /// # Errors
    ///
    /// * `BuildError::EncodingError` if encoding the payload fails
    /// * `BuildError::SigningError` if signing fails
    ///
    /// # Panics
    ///
    /// Panics if random number generator fails when generating a nonce.
    /// This will never happen if a nonce is provided, and is not recoverable
    /// because a broken RNG is a serious problem.
    ///
    /// # Example
    ///
    /// ```ignore
    /// let signer = Ed25519Signer::new(signing_key);
    /// let invocation = InvocationBuilder::new()
    ///     .issuer(signer)
    ///     .audience(audience_did)
    ///     .subject(subject_did)
    ///     .command(vec!["storage".into(), "read".into()])
    ///     .proofs(vec![delegation_cid])
    ///     .try_build()
    ///     .await?;
    /// ```
    #[allow(clippy::expect_used)]
    pub async fn try_build(self) -> Result<super::Invocation<D::Principal>, BuildError> {
        let payload: super::InvocationPayload<D::Principal> = super::InvocationPayload {
            issuer: self.issuer.principal().clone(),
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            expiration: self.expiration,
            issued_at: self.issued_at,
            proofs: self.proofs,
            cause: self.cause,
            meta: self.meta,
            nonce: self
                .nonce
                .unwrap_or_else(|| Nonce::generate_16().expect("failed to generate nonce")),
        };

        let header: Varsig<
            <D::Principal as Verifier>::Algorithm,
            CborCodec,
            super::InvocationPayload<D::Principal>,
        > = Varsig::new(CborCodec);

        // Encode and sign the payload
        let encoded = header
            .encode(&payload)
            .map_err(|e| BuildError::EncodingError(e.to_string()))?;
        let sig = self
            .issuer
            .sign(&encoded)
            .await
            .map_err(BuildError::SigningError)?;

        let payload: EnvelopePayload<
            <D::Principal as Verifier>::Algorithm,
            super::InvocationPayload<D::Principal>,
        > = EnvelopePayload { header, payload };

        #[allow(clippy::type_complexity)]
        let envelope: Envelope<
            <D::Principal as Verifier>::Algorithm,
            super::InvocationPayload<D::Principal>,
            <<D::Principal as Verifier>::Algorithm as SignatureAlgorithm>::Signature,
        > = Envelope(sig, payload);

        let invocation: super::Invocation<D::Principal> = super::Invocation(envelope);

        Ok(invocation)
    }
}
