//! Typesafe builder for [`Invocation`].

use crate::{
    command::Command,
    crypto::nonce::Nonce,
    envelope::{Envelope, EnvelopePayload},
    issuer::Issuer,
    promise::Promised,
    sealed::{CommandOrUnset, DidOrUnset, IssuerOrUnset, ProofsOrUnset},
    time::timestamp::Timestamp,
    unset::Unset,
};
use ipld_core::{cid::Cid, ipld::Ipld};
use std::{collections::BTreeMap, marker::PhantomData};
use varsig::{Did, Principal, Signature, Signer};

/// Typesafe builder for [`Invocation`][super::Invocation].
///
/// `S` is the signature type. Type parameters track which required
/// fields have been set; call `.try_build()` once all are provided.
#[derive(Default, Debug, Clone)]
pub struct InvocationBuilder<
    S: Signature,
    Iss: IssuerOrUnset<S> = Unset,
    Audience: DidOrUnset = Unset,
    Subject: DidOrUnset = Unset,
    Cmd: CommandOrUnset = Unset,
    Proofs: ProofsOrUnset = Unset,
> {
    /// Issuer of the invocation.
    pub issuer: Iss,

    /// Audience of the invocation.
    pub audience: Audience,

    /// Subject of the invocation (the resource or object being accessed).
    pub subject: Subject,

    /// Command being invoked.
    pub command: Cmd,

    /// The arguments for the command.
    pub arguments: BTreeMap<String, Promised>,

    /// Proofs of the invocation.
    pub proofs: Proofs,

    /// Cause of the invocation.
    pub cause: Option<Cid>,

    /// Expiration time of the invocation.
    pub expiration: Option<Timestamp>,

    /// The time at which this invocation claims to have been issued.
    pub issued_at: Option<Timestamp>,

    /// Extensible metadata for the invocation.
    pub meta: BTreeMap<String, Ipld>,

    /// Nonce (will be autogenerated if left blank).
    pub nonce: Option<Nonce>,

    _sig: PhantomData<S>,
}

impl<S: Signature> InvocationBuilder<S> {
    /// Creates a blank [`InvocationBuilder`] instance.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            issuer: Unset,
            audience: Unset,
            subject: Unset,
            command: Unset,
            arguments: BTreeMap::new(),
            proofs: Unset,
            cause: None,
            expiration: None,
            issued_at: None,
            meta: BTreeMap::new(),
            nonce: None,
            _sig: PhantomData,
        }
    }
}

#[allow(private_bounds)]
impl<
        S: Signature,
        Iss: IssuerOrUnset<S>,
        Audience: DidOrUnset,
        Subject: DidOrUnset,
        Cmd: CommandOrUnset,
        Proofs: ProofsOrUnset,
    > InvocationBuilder<S, Iss, Audience, Subject, Cmd, Proofs>
{
    /// Sets the issuer (signer) of the invocation.
    #[must_use]
    pub fn issuer<I: Issuer<S>>(
        self,
        issuer: I,
    ) -> InvocationBuilder<S, I, Audience, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _sig: PhantomData,
        }
    }

    /// Sets the `audience` field of the invocation.
    #[must_use]
    pub fn audience(
        self,
        audience: &impl Principal,
    ) -> InvocationBuilder<S, Iss, Did, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: audience.did(),
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _sig: PhantomData,
        }
    }

    /// Sets the `subject` field of the invocation.
    #[must_use]
    pub fn subject(
        self,
        subject: &impl Principal,
    ) -> InvocationBuilder<S, Iss, Audience, Did, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: subject.did(),
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _sig: PhantomData,
        }
    }

    /// Sets the `command` field of the invocation.
    #[must_use]
    pub fn command(
        self,
        command: Vec<String>,
    ) -> InvocationBuilder<S, Iss, Audience, Subject, Command, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: Command::new(command),
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _sig: PhantomData,
        }
    }

    /// Sets the `arguments` field of the invocation.
    #[must_use]
    pub fn arguments(
        self,
        arguments: BTreeMap<String, Promised>,
    ) -> InvocationBuilder<S, Iss, Audience, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _sig: PhantomData,
        }
    }

    /// Sets the `proofs` field of the invocation.
    #[must_use]
    pub fn proofs(
        self,
        proofs: Vec<Cid>,
    ) -> InvocationBuilder<S, Iss, Audience, Subject, Cmd, Vec<Cid>> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _sig: PhantomData,
        }
    }

    /// Sets the `expiration` field of the invocation.
    #[must_use]
    pub fn expiration(
        self,
        expiration: Timestamp,
    ) -> InvocationBuilder<S, Iss, Audience, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: Some(expiration),
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _sig: PhantomData,
        }
    }

    /// Sets the `issued_at` field of the invocation.
    #[must_use]
    pub fn issued_at(
        self,
        issued_at: Timestamp,
    ) -> InvocationBuilder<S, Iss, Audience, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: Some(issued_at),
            meta: self.meta,
            nonce: self.nonce,
            _sig: PhantomData,
        }
    }

    /// Sets the `issued_at` field of the invocation to the current system time.
    #[must_use]
    pub fn issue_now(self) -> InvocationBuilder<S, Iss, Audience, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: Some(Timestamp::now()),
            meta: self.meta,
            nonce: self.nonce,
            _sig: PhantomData,
        }
    }

    /// Sets the `meta` field of the invocation.
    #[must_use]
    pub fn meta(
        self,
        meta: BTreeMap<String, Ipld>,
    ) -> InvocationBuilder<S, Iss, Audience, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta,
            nonce: self.nonce,
            _sig: PhantomData,
        }
    }

    /// Sets the `nonce` field of the invocation.
    #[must_use]
    pub fn nonce(self, nonce: Nonce) -> InvocationBuilder<S, Iss, Audience, Subject, Cmd, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: Some(nonce),
            _sig: PhantomData,
        }
    }
}

/// Build error type for invocation builder.
#[derive(Debug, thiserror::Error)]
pub enum BuildError {
    /// Encoding error.
    #[error("Encoding error: {0}")]
    EncodingError(String),

    /// Signing error.
    #[error("Signing error: {0}")]
    SigningError(#[from] signature::Error),
}

impl<S: Signature, I: Issuer<S>> InvocationBuilder<S, I, Did, Did, Command, Vec<Cid>> {
    /// Builds the complete, signed [`Invocation`].
    ///
    /// Uses the issuer (set via `.issuer()`) to sign the invocation.
    /// The signing is performed asynchronously via [`Signer::sign()`][varsig::signature::Signer::sign].
    ///
    /// # Errors
    ///
    /// * [`BuildError::EncodingError`] if encoding the payload fails
    /// * [`BuildError::SigningError`] if signing fails
    ///
    /// # Panics
    ///
    /// Panics if random number generator fails when generating a nonce.
    /// This will never happen if a nonce is provided, and is not recoverable
    /// because a broken RNG is a serious problem.
    ///
    /// # Example
    ///
    /// ```ignore
    /// let invocation = InvocationBuilder::new()
    ///     .issuer(signer)
    ///     .audience(&audience_did)
    ///     .subject(&subject_did)
    ///     .command(vec!["storage".into(), "read".into()])
    ///     .proofs(vec![delegation_cid])
    ///     .try_build()
    ///     .await?;
    /// ```
    #[allow(clippy::expect_used)]
    pub async fn try_build(self) -> Result<super::Invocation<S>, BuildError> {
        let audience = if self.audience == self.subject {
            None
        } else {
            Some(self.audience)
        };
        let payload = super::InvocationPayload {
            issuer: self.issuer.did(),
            audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: if self.meta.is_empty() {
                None
            } else {
                Some(self.meta)
            },
            nonce: self
                .nonce
                .unwrap_or_else(|| Nonce::generate_16().expect("failed to generate nonce")),
        };

        let envelope = EnvelopePayload::from(payload);

        let encoded = envelope
            .encode()
            .map_err(|e| BuildError::EncodingError(e.to_string()))?;

        let sig = Signer::sign(&self.issuer, &encoded)
            .await
            .map_err(BuildError::SigningError)?;

        Ok(super::Invocation(Envelope(sig, envelope)))
    }
}
