//! Typesafe builder for [`Invocation`].

use crate::{
    crypto::nonce::Nonce,
    did::Did,
    promise::Promised,
    sealed::{CommandOrUnset, DidOrUnset, ProofsOrUnset},
    time::timestamp::Timestamp,
    unset::Unset,
};
use ipld_core::{cid::Cid, ipld::Ipld};
use std::{collections::BTreeMap, marker::PhantomData};

/// Typesafe builder for [`Delegation`].
#[derive(Default, Debug, Clone)]
pub struct InvocationBuilder<
    D: Did,
    Issuer: DidOrUnset = Unset,
    Audience: DidOrUnset = Unset,
    Subject: DidOrUnset = Unset,
    Command: CommandOrUnset = Unset,
    Proofs: ProofsOrUnset = Unset,
> {
    /// Issuer of the invocation.
    pub issuer: Issuer,

    /// Audience of the invocation.
    pub audience: Audience,

    /// Subject of the invocation (the resource or object being accessed).
    pub subject: Subject,

    /// Command being invoked.
    pub command: Command,

    /// The arguments for the Command.
    pub arguments: BTreeMap<String, Promised>,

    /// Proofs of the invocation.
    pub proofs: Proofs,

    /// Cause of the invocation.
    pub cause: Option<Cid>,

    /// Expiration time of the invocation.
    pub expiration: Option<Timestamp>,

    /// The time at which this invocation claims to have been issued.
    pub issued_at: Option<Timestamp>,

    /// Extensible metadata for the delegation.
    pub meta: BTreeMap<String, Ipld>,

    /// Nonce (will be autogenerated if left blank).
    pub nonce: Option<Nonce>,

    _did: PhantomData<D>,
}

impl<D: Did> InvocationBuilder<D, Unset, Unset, Unset, Unset, Unset> {
    /// Creates a blank [`InvocationBuilder`] instance.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            issuer: Unset,
            audience: Unset,
            subject: Unset,
            command: Unset,
            arguments: BTreeMap::new(),
            proofs: Unset,
            cause: None,
            expiration: None,
            issued_at: None,
            meta: BTreeMap::new(),
            nonce: None,
            _did: PhantomData,
        }
    }
}

impl<
        D: Did,
        Issuer: DidOrUnset,
        Audience: DidOrUnset,
        Subject: DidOrUnset,
        Command: CommandOrUnset,
        Proofs: ProofsOrUnset,
    > InvocationBuilder<D, Issuer, Audience, Subject, Command, Proofs>
{
    /// Sets the `issuer` field of the invocation.
    #[must_use]
    pub fn issuer(self, issuer: D) -> InvocationBuilder<D, D, Audience, Subject, Command, Proofs> {
        InvocationBuilder {
            issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `audience` field of the invocation.
    #[must_use]
    pub fn audience(
        self,
        audience: D,
    ) -> InvocationBuilder<D, Issuer, D, Subject, Command, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `subject` field of the invocation.
    #[must_use]
    pub fn subject(self, subject: D) -> InvocationBuilder<D, Issuer, Audience, D, Command, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `command` field of the invocation.
    #[must_use]
    pub fn command(
        self,
        command: Vec<String>,
    ) -> InvocationBuilder<D, Issuer, Audience, Subject, Vec<String>, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `arguments` field of the invocation.
    #[must_use]
    pub fn arguments(
        self,
        arguments: BTreeMap<String, Promised>,
    ) -> InvocationBuilder<D, Issuer, Audience, Subject, Command, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `proofs` field of the invocation.
    #[must_use]
    pub fn proofs(
        self,
        proofs: Vec<Cid>,
    ) -> InvocationBuilder<D, Issuer, Audience, Subject, Command, Vec<Cid>> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `expiration` field of the invocation.
    #[must_use]
    pub fn expiration(
        self,
        expiration: Timestamp,
    ) -> InvocationBuilder<D, Issuer, Audience, Subject, Command, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: Some(expiration),
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `issued_at` field of the invocation.
    #[must_use]
    pub fn issued_at(
        self,
        issued_at: Timestamp,
    ) -> InvocationBuilder<D, Issuer, Audience, Subject, Command, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: Some(issued_at),
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `issued_at` field of the invocation to the current system time.
    #[must_use]
    pub fn issue_now(self) -> InvocationBuilder<D, Issuer, Audience, Subject, Command, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: Some(Timestamp::now()),
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `meta` field of the invocation.
    #[must_use]
    pub fn meta(
        self,
        meta: BTreeMap<String, Ipld>,
    ) -> InvocationBuilder<D, Issuer, Audience, Subject, Command, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `nonce` field of the invocation.
    #[must_use]
    pub fn nonce(
        self,
        nonce: Nonce,
    ) -> InvocationBuilder<D, Issuer, Audience, Subject, Command, Proofs> {
        InvocationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: Some(nonce),
            _did: PhantomData,
        }
    }
}

#[allow(clippy::mismatching_type_param_order)]
impl<D: Did> InvocationBuilder<D, D, D, D, Vec<String>, Vec<Cid>> {
    /// Builds the [`Delegation`] instance from the builder.
    ///
    /// This is typesafe, and only possible to call when all required fields are set.
    ///
    /// # Panics
    ///
    /// Panics if random number generator fails when generating a nonce.
    /// This will never happen if a nonce is provided, and is not recoverable
    /// becuase a broken RNG is a serious problem.
    #[allow(clippy::expect_used)]
    pub fn build(self) -> super::Invocation<D> {
        super::Invocation {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            arguments: self.arguments,
            proofs: self.proofs,
            cause: self.cause,
            expiration: self.expiration,
            issued_at: self.issued_at,
            meta: self.meta,
            nonce: self
                .nonce
                .unwrap_or_else(|| Nonce::generate_16().expect("failed to generate nonce")),
        }
    }

    // pub fn try_sign(self) -> Signed<Delegation> {
    //     todo!()
    // }
}
