//! Typesafe builder for [`Delegation`].

use super::{policy::predicate::Predicate, subject::DelegatedSubject};
use crate::{
    command::Command,
    crypto::nonce::Nonce,
    principal::{Issuer, Principal},
    envelope::{Envelope, EnvelopePayload},
    sealed::{CommandOrUnset, DelegatedSubjectOrUnset, IssuerOrUnset, PrincipalOrUnset},
    time::timestamp::Timestamp,
    unset::Unset,
};
use ipld_core::ipld::Ipld;
use serde_ipld_dagcbor::codec::DagCborCodec;
use std::{collections::BTreeMap, marker::PhantomData};
use varsig::{
    signature::SignError,
    algorithm::SignatureAlgorithm,
    Varsig,
};

/// Typesafe builder for [`Delegation`][super::Delegation].
#[derive(Default, Debug, Clone)]
pub struct DelegationBuilder<
    D: Issuer,
    Iss: IssuerOrUnset = Unset,
    Audience: PrincipalOrUnset = Unset,
    Subject: DelegatedSubjectOrUnset = Unset,
    Cmd: CommandOrUnset = Unset,
> {
    /// Issuer of the delegation.
    pub issuer: Iss,

    /// Audience of the delegation.
    pub audience: Audience,

    /// Subject of the delegation (the resource or object being accessed).
    pub subject: Subject,

    /// Command of the delegation (similar to a function name).
    pub command: Cmd,

    /// Policy of the delegation.
    ///
    /// A list of predicates that the [`Invocation`] arguments must satisfy.
    pub policy: Vec<Predicate>,

    /// Expiration time of the delegation.
    pub expiration: Option<Timestamp>,

    /// Earliest time a delegation can be used.
    pub not_before: Option<Timestamp>,

    /// Extensible metadata for the delegation.
    pub meta: BTreeMap<String, Ipld>,

    /// Nonce (will be autogenerated if left blank).
    pub nonce: Option<Nonce>,

    _did: PhantomData<D>,
}

impl<D: Issuer> DelegationBuilder<D> {
    /// Creates a blank [`DelegationBuilder`] instance.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            issuer: Unset,
            audience: Unset,
            subject: Unset,
            command: Unset,
            policy: Vec::new(),
            expiration: None,
            not_before: None,
            meta: BTreeMap::new(),
            nonce: None,
            _did: PhantomData,
        }
    }
}

#[allow(private_bounds)]
impl<
        D: Issuer,
        Iss: IssuerOrUnset,
        Audience: PrincipalOrUnset,
        Subject: DelegatedSubjectOrUnset,
        Cmd: CommandOrUnset,
    > DelegationBuilder<D, Iss, Audience, Subject, Cmd>
{
    /// Sets the `issuer` field of the delegation.
    #[must_use]
    pub fn issuer(self, issuer: D) -> DelegationBuilder<D, D, Audience, Subject, Cmd> {
        DelegationBuilder {
            issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            policy: self.policy,
            expiration: self.expiration,
            not_before: self.not_before,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `audience` field of the delegation.
    #[must_use]
    pub fn audience(self, audience: D::Principal) -> DelegationBuilder<D, Iss, D::Principal, Subject, Cmd> {
        DelegationBuilder {
            issuer: self.issuer,
            audience,
            subject: self.subject,
            command: self.command,
            policy: self.policy,
            expiration: self.expiration,
            not_before: self.not_before,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `subject` field of the delegation.
    #[must_use]
    pub fn subject(
        self,
        subject: DelegatedSubject<D::Principal>,
    ) -> DelegationBuilder<D, Iss, Audience, DelegatedSubject<D::Principal>, Cmd> {
        DelegationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject,
            command: self.command,
            policy: self.policy,
            expiration: self.expiration,
            not_before: self.not_before,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `command` field of the delegation.
    #[must_use]
    pub fn command(
        self,
        command: Vec<String>,
    ) -> DelegationBuilder<D, Iss, Audience, Subject, Command> {
        DelegationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: Command::new(command),
            policy: self.policy,
            expiration: self.expiration,
            not_before: self.not_before,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `policy` field of the delegation.
    #[must_use]
    pub fn policy(
        self,
        policy: Vec<Predicate>,
    ) -> DelegationBuilder<D, Iss, Audience, Subject, Cmd> {
        DelegationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            policy,
            expiration: self.expiration,
            not_before: self.not_before,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `expiration` field of the delegation.
    #[must_use]
    pub fn expiration(
        self,
        expiration: Timestamp,
    ) -> DelegationBuilder<D, Iss, Audience, Subject, Cmd> {
        DelegationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            policy: self.policy,
            expiration: Some(expiration),
            not_before: self.not_before,
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `not_before` field of the delegation.
    #[must_use]
    pub fn not_before(
        self,
        not_before: Timestamp,
    ) -> DelegationBuilder<D, Iss, Audience, Subject, Cmd> {
        DelegationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            policy: self.policy,
            expiration: self.expiration,
            not_before: Some(not_before),
            meta: self.meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `meta` field of the delegation.
    #[must_use]
    pub fn meta(
        self,
        meta: BTreeMap<String, Ipld>,
    ) -> DelegationBuilder<D, Iss, Audience, Subject, Cmd> {
        DelegationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            policy: self.policy,
            expiration: self.expiration,
            not_before: self.not_before,
            meta,
            nonce: self.nonce,
            _did: PhantomData,
        }
    }

    /// Sets the `nonce` field of the delegation.
    #[must_use]
    pub fn nonce(self, nonce: Nonce) -> DelegationBuilder<D, Iss, Audience, Subject, Cmd> {
        DelegationBuilder {
            issuer: self.issuer,
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            policy: self.policy,
            expiration: self.expiration,
            not_before: self.not_before,
            meta: self.meta,
            nonce: Some(nonce),
            _did: PhantomData,
        }
    }
}

/// Build error type for delegation builder.
#[derive(Debug, thiserror::Error)]
pub enum BuildError {
    /// Encoding error.
    #[error("Encoding error: {0}")]
    EncodingError(String),

    /// Signing error.
    #[error("Signing error: {0}")]
    SigningError(#[from] signature::Error),
}

impl<E: std::error::Error> From<SignError<E>> for BuildError {
    fn from(e: SignError<E>) -> Self {
        match e {
            SignError::EncodingError(e) => BuildError::EncodingError(e.to_string()),
            SignError::SigningError(e) => BuildError::SigningError(e),
        }
    }
}

/// Building methods that use async signing.
///
/// This impl block uses async signing via the [`Issuer`] trait (which is a `Signer`),
/// which works with both native `ed25519_dalek` signers and `WebCrypto` signers.
#[allow(clippy::mismatching_type_param_order)]
impl<D: Issuer> DelegationBuilder<D, D, D::Principal, DelegatedSubject<D::Principal>, Command> {
    /// Builds the complete, signed [`Delegation`].
    ///
    /// Uses the issuer's signer (set via `.issuer()`) to sign the delegation.
    /// The signing is performed asynchronously via `Signer::sign()`.
    ///
    /// # Errors
    ///
    /// * `BuildError::EncodingError` if encoding the payload fails
    /// * `BuildError::SigningError` if signing fails
    ///
    /// # Panics
    ///
    /// Panics if random number generator fails when generating a nonce.
    /// This will never happen if a nonce is provided, and is not recoverable
    /// because a broken RNG is a serious problem.
    ///
    /// # Example
    ///
    /// ```ignore
    /// let signer = Ed25519Signer::new(signing_key);
    /// let delegation = DelegationBuilder::new()
    ///     .issuer(signer)
    ///     .audience(audience_did)
    ///     .subject(DelegatedSubject::Any)
    ///     .command(vec!["storage".into(), "read".into()])
    ///     .try_build()
    ///     .await?;
    /// ```
    #[allow(clippy::expect_used)]
    pub async fn try_build(self) -> Result<super::Delegation<D::Principal>, BuildError> {
        let payload: super::DelegationPayload<D::Principal> = super::DelegationPayload {
            issuer: self.issuer.principal().clone(),
            audience: self.audience,
            subject: self.subject,
            command: self.command,
            policy: self.policy,
            expiration: self.expiration,
            not_before: self.not_before,
            meta: self.meta,
            nonce: self
                .nonce
                .unwrap_or_else(|| Nonce::generate_16().expect("failed to generate nonce")),
        };

        let header: Varsig<
            <D::Principal as Principal>::Algorithm,
            DagCborCodec,
            super::DelegationPayload<D::Principal>,
        > = Varsig::new(DagCborCodec);

        // Sign the payload
        let (sig, _encoded) = header.sign(&self.issuer, &payload).await?;

        let payload: EnvelopePayload<
            <D::Principal as Principal>::Algorithm,
            super::DelegationPayload<D::Principal>,
        > = EnvelopePayload { header, payload };

        #[allow(clippy::type_complexity)]
        let envelope: Envelope<
            <D::Principal as Principal>::Algorithm,
            super::DelegationPayload<D::Principal>,
            <<D::Principal as Principal>::Algorithm as SignatureAlgorithm>::Signature,
        > = Envelope(sig, payload);

        let delegation: super::Delegation<D::Principal> = super::Delegation(envelope);

        Ok(delegation)
    }
}
